### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by jsf9k** [cisagov/ioc-scanner#16]
# 💥 Regression Report

Our APB runs on this repository keep erroring out because of some failed tests.  See [this APB run](https://github.com/cisagov/ioc-scanner/runs/1054706095?check_suite_focus=true), for example.

## Last working version

Looks like [this](https://github.com/cisagov/ioc-scanner/actions/runs/181727101) was the last build that succeeded.

## To Reproduce

- Check out the repo from scratch
- Install Python dependencies
- Run tests

## Expected behavior

All tests should pass.

**Comment by mcdonnnj** [comment]
The build issues between `pytest` and `pyfakefs` was resolved in merged in #15
