### ISSUE TITLE
Support Hashes in external file

### ISSUE THREAD

**Issue by bra1ncramp** [cisagov/ioc-scanner#7]
# 🚀 Feature Proposal

Instead of having the list of hashes located in ioc_scanner.py block, we would ideally be able to point to a text file (as is done with the hosts-file). 

## Motivation
Don't have to edit a python file each time you want to look for a new hash

## Pitch

Because it currently is somewhat cumbersome. and could be improved :)

**Comment by mcdonnnj** [comment]
@bra1ncramp You should be able to reference a file using the `--file` option. The default blob in `ioc_scanner.py` is only used if one it not provided per:
https://github.com/cisagov/ioc-scanner/blob/b1e27cde941d840983360c947c2792fa2feb4f77/src/ioc_scan/ioc_scanner.py#L82-L83

The `--stdin` and `--file` options can be used to provide hashes, and they will be passed to `ioc_scanner.py` per:
https://github.com/cisagov/ioc-scanner/blob/b1e27cde941d840983360c947c2792fa2feb4f77/src/ioc_scan/ioc_scan_cli.py#L50-L60

**Comment by bra1ncramp** [comment]
--file references the hosts

**Comment by mcdonnnj** [comment]
How are you currently calling the script? As I read it the `--stdin` and `--file` options set hashes other than the defaults set in the `BLOB` constant in `ioc_scanner.py`.

**Comment by bra1ncramp** [comment]
Yep, that's what it says. I should have read more. I'll try it out tomorrow.

**Comment by mcdonnnj** [comment]
I do think the usage for `--file` and `--stdin` could be improved, because reading just the usage it was unclear to me that you could use those options to provide hashes.

**Comment by bra1ncramp** [comment]
That switch doesn't work with the ansible script, which is necessary when running it remotely across multiple hosts.

**Comment by bra1ncramp** [comment]
```
$ ansible -i hosts-file all -m script -a ./src/ioc_scan/ioc_scanner.py --file md5sums.txt --become
usage: ansible [-h] [--version] [-v] [-b] [--become-method BECOME_METHOD] [--become-user BECOME_USER] [-K] [-i INVENTORY] [--list-hosts] [-l SUBSET] [-P POLL_INTERVAL]
               [-B SECONDS] [-o] [-t TREE] [-k] [--private-key PRIVATE_KEY_FILE] [-u REMOTE_USER] [-c CONNECTION] [-T TIMEOUT] [--ssh-common-args SSH_COMMON_ARGS]
               [--sftp-extra-args SFTP_EXTRA_ARGS] [--scp-extra-args SCP_EXTRA_ARGS] [--ssh-extra-args SSH_EXTRA_ARGS] [-C] [--syntax-check] [-D] [-e EXTRA_VARS]
               [--vault-id VAULT_IDS] [--ask-vault-pass | --vault-password-file VAULT_PASSWORD_FILES] [-f FORKS] [-M MODULE_PATH] [--playbook-dir BASEDIR] [-a MODULE_ARGS]
               [-m MODULE_NAME]
               pattern
ansible: error: unrecognized arguments: --file md5sums.txt
```

**Comment by bra1ncramp** [comment]
Nevermind - I figured it out

`ansible -i hosts-file all -m script -e "--file md5sums.txt"  -a ./src/ioc_scan/ioc_scanner.py  --become`

**Comment by jsf9k** [comment]
This issue is closed, since @bra1ncramp's is resolved.  Instead I created #8 for improving the usage info around the `--file` and `--stdin` flags.
