### ISSUE TITLE
Improve usage information

### ISSUE THREAD

**Issue by jsf9k** [cisagov/ioc-scanner#8]
# 🚀 Feature Proposal

Improve the usage information for `--file` and `--stdin`.

## Motivation

As @mcdonnnj pointed out in #7:
> I do think the usage for `--file` and `--stdin` could be improved, because reading just the usage it was unclear to me that you could use those options to provide hashes.

## Example

It would reduce the sort of confusion that generated #7.

## Pitch

Eschew obfuscation!

**Comment by jsf9k** [comment]
@hillaryj also mentioned that the CLI should barf if it gets command line arguments that it does not expect.

**Comment by mcdonnnj** [comment]
We could leverage [Schema](https://github.com/keleshev/schema), which we already use in [cisagov/skeleton-python-library](https://github.com/cisagov/skeleton-python-library).

**Comment by mcdonnnj** [comment]
> @hillaryj also mentioned that the CLI should barf if it gets command line arguments that it does not expect.

I spaced when I first read this comment. Since we use [docopt](https://github.com/docopt/docopt) for command line arguments, it will already print usage and exit if it receives unexpected command line arguments.

Supported use:
```console
$ ioc-scan --target=README.md
Scan elapsed time: 0:00:00.005877
Hit count by indicators:
70a6058952ed3212217105ec7865ba21    0
dff4b51907018f5cf325120aec2caf45    0
2d7a648ebe64e536944c011c8dcbb375    0
132646a2ad9deac1944be4264da30b01    0
8c109784750142b158a1459751ae5faf    0
fff485a90ef0a86fb2813eb64fd3442c    0
2d7a648ebe64e536944c011c8dcbb375    0
2a2410cef5497cbd3f6c13eaff9619da    0
3e7eb6abcce304de0822a618de756fd2    0
350cba65e28c723cbf0724c19bd7ee69    0
0313fd399b143fc40cd52a1679018305    0
ac56f4b8fac5739ccdb45777d313becf    0
69630e4574ec6798239b091cda43dca0    0
31b54aebdaf5fbc73a66ac41ccb35943cc9b7f72    0
50973a3fc57d70c7911f7a952356188b9939e56b    0
244eb62b9ac30934098ca4204447440d6fc4e259    0
5c8f83cc4ff57e7c67925df4d9daabe5d0cc07e2    0
b509f8545501588ecd828f970d91afc7c4aa6e238e838bd6a08ee2cd920fbe98    0
```

Unexpected argument:
```console
$ ioc-scan --foo --target=README.md
Usage:
  ioc-scan [--log-level=LEVEL] [--stdin | --file=hashfile] [--target=root]
  ioc-scan (-h | --help)
```

Are we trying to go beyond this?

**Comment by hillaryj** [comment]
That's enough - in the original discussion you mentioned that it accepted an argument without doing anything with it, which is what the "reject unexpected arguments" point was about. If it didn't do anything with the arg because the file wasn't the right type, it should error/complain about an incompatible file being specified.
